export function mcpRouteTemplate(siteName: string): string {
  return [
    'import { NextResponse } from "next/server";',
    'import { z } from "zod";',
    "",
    "// Minimal, read-only MCP scaffold: initialize / ping / tools/list / tools/call.",
    "// No tools are registered yet — wire up real, read-only tools as needed.",
    "// Requires the `zod` package in this project (npm install zod).",
    "",
    "const jsonRpcRequestSchema = z.object({",
    '  jsonrpc: z.literal("2.0"),',
    "  id: z.union([z.string(), z.number(), z.null()]).optional(),",
    "  method: z.string(),",
    "  params: z.unknown().optional(),",
    "});",
    "",
    "const TOOLS: Array<{ name: string; description: string; inputSchema: Record<string, unknown> }> = [];",
    "",
    "function rpcResult(id: unknown, result: unknown) {",
    '  return NextResponse.json({ jsonrpc: "2.0", id, result });',
    "}",
    "",
    "function rpcError(id: unknown, code: number, message: string) {",
    "  return NextResponse.json(",
    '    { jsonrpc: "2.0", id: id ?? null, error: { code, message } },',
    "    { status: 200 },",
    "  );",
    "}",
    "",
    "export async function POST(request: Request) {",
    "  let body: unknown;",
    "  try {",
    "    body = await request.json();",
    "  } catch {",
    '    return rpcError(null, -32700, "Parse error");',
    "  }",
    "",
    "  const parsed = jsonRpcRequestSchema.safeParse(body);",
    "  if (!parsed.success) {",
    "    const maybeId = (body as { id?: unknown } | null)?.id;",
    '    return rpcError(maybeId, -32600, "Invalid Request");',
    "  }",
    "",
    "  const { id, method, params } = parsed.data;",
    "",
    "  switch (method) {",
    '    case "initialize":',
    "      return rpcResult(id, {",
    '        protocolVersion: "2026-01-01",',
    `        serverInfo: { name: "${siteName}", version: "0.1.0" },`,
    "        capabilities: { tools: {} },",
    "      });",
    '    case "ping":',
    "      return rpcResult(id, {});",
    '    case "tools/list":',
    "      return rpcResult(id, { tools: TOOLS });",
    '    case "tools/call": {',
    "      const callSchema = z.object({",
    "        name: z.string(),",
    "        arguments: z.record(z.string(), z.unknown()).optional(),",
    "      });",
    "      const call = callSchema.safeParse(params);",
    "      if (!call.success) {",
    '        return rpcError(id, -32602, "Invalid params");',
    "      }",
    "      return rpcError(id, -32601, `Unknown tool: ${call.data.name}`);",
    "    }",
    "    default:",
    '      return rpcError(id, -32601, "Method not found");',
    "  }",
    "}",
    "",
    "export function GET() {",
    "  return NextResponse.json({",
    `    name: "${siteName} MCP endpoint",`,
    '    protocol: "mcp",',
    '    transport: "json-rpc-2.0-over-http",',
    '    methods: ["initialize", "ping", "tools/list", "tools/call"],',
    "  });",
    "}",
    "",
  ].join("\n");
}
