export type TrustPageKind = "about" | "contact" | "privacy";

const COPY: Record<TrustPageKind, { title: string; description: string; body: string[] }> = {
  about: {
    title: "About",
    description: "Learn what this site is, who runs it, and how it works.",
    body: [
      "This page exists so that both people and AI agents can quickly understand what this site is and who stands behind it. A clear, crawlable About page is one of the fastest ways to build trust with a visitor who has never seen the site before, whether that visitor is a human reading in a browser or an agent summarizing the page on someone&apos;s behalf.",
      "Use this space to describe the organization&apos;s mission, the problem it solves, and the people or team behind it. Agents that are asked to evaluate, cite, or recommend a site look for exactly this kind of plain-language context: what the site does, why it exists, and why it can be trusted. Avoid burying this information behind client-side interactions or images with no text alternative, since that makes it invisible to anything that cannot execute arbitrary JavaScript or read pixels.",
      "A good About page also links out to the other trust signals a reader or agent might look for next: contact details, a privacy policy, and any relevant credentials or history. Keeping those links close together, and reachable from a real HTML anchor tag rather than a JavaScript-only handler, makes the whole site easier to navigate for both audiences.",
      "This content is placeholder copy generated by loop2agentic. Replace it with real information about your organization before shipping to production.",
    ],
  },
  contact: {
    title: "Contact",
    description: "How to reach this site's owners, and what to expect when you do.",
    body: [
      "This page exists so that a visitor, or an agent acting for a visitor, can find a reliable way to get in touch. A missing or hard-to-find contact page is one of the most common reasons a site scores poorly on agent-readiness and trust audits alike, since it signals that there may be no accountable party behind the content.",
      "Use this space to list a real support channel: an email address, a contact form, a support ticket system, or a mailing address, depending on what fits the organization. Where possible, prefer a plain link or a simple HTML form over a contact flow that requires JavaScript to render, so that the information remains visible to text-based tools and simple crawlers.",
      "It also helps to set expectations here: what kind of requests this channel handles, and how quickly someone can expect a response. That context lets both human visitors and automated agents route their request correctly the first time, instead of guessing or giving up.",
      "This content is placeholder copy generated by loop2agentic. Replace it with real contact information before shipping to production.",
    ],
  },
  privacy: {
    title: "Privacy",
    description: "What data this site collects, why, and how it is handled.",
    body: [
      "This page exists so that visitors, including AI agents evaluating the site on a user&apos;s behalf, can understand what information is collected and how it is used. A visible, plain-language privacy policy is table stakes for a trustworthy site, and its absence is treated as a red flag by most agent-readiness and compliance audits.",
      "Use this space to describe what data is collected (for example, analytics, cookies, or account information), why it is collected, how long it is retained, and who it may be shared with. Where the site integrates third-party services such as analytics or payment processors, name them explicitly rather than referring only to a generic &lsquo;partners&rsquo; clause.",
      "It also helps to explain what choices a visitor has: how to opt out of tracking, how to request deletion of their data, and who to contact with privacy questions. Linking to the Contact page from here closes the loop and makes the policy actionable rather than purely informational.",
      "This content is placeholder copy generated by loop2agentic. Replace it with a real, reviewed privacy policy before shipping to production.",
    ],
  },
};

export function trustPageTemplate(kind: TrustPageKind, siteName: string, baseUrl: string): string {
  const copy = COPY[kind];
  const base = baseUrl.replace(/\/$/, "");
  const canonical = `${base}/${kind}`;
  const paragraphs = copy.body.map((paragraph) => `      <p>${paragraph}</p>`).join("\n");

  return [
    'import type { Metadata } from "next";',
    "",
    "export const metadata: Metadata = {",
    `  title: "${copy.title} | ${siteName}",`,
    `  description: "${copy.description}",`,
    "  alternates: {",
    `    canonical: "${canonical}",`,
    "  },",
    "};",
    "",
    `export default function ${capitalize(kind)}Page() {`,
    "  return (",
    "    <main>",
    `      <h1>${copy.title}</h1>`,
    paragraphs,
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function capitalize(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
